### PR TITLE
Draft: Zink / Mill integration: the Zebra Shut the Door

### PR DESCRIPTION
**Pull request by tacryt-socryp**
mill/zink: implement generic +slam on doors called +shut, implement +zebra which is bounded zk equivalent of +mule.

Also implemented partial eval of +shut specifically for use in mill, this one is called +ajar.

### CODE REVIEW

**Review by dr-frmr — APPROVED** [review]
Do you want me to try loading in a real contract on this and running it, or are we good?

**Comment by dr-frmr** [comment]
Ok sounds great, I'm down

**Comment by dr-frmr** [comment]
Update with @tacryt-socryp: this works perfectly and now it's just a matter of pre-hashing smart.hoon and building a cache for contracts so they only need to be hashed once. We discussed adding a gas decrement on every traversed hash, not just those that aren't in the cache. This will fix a potential infinite loop issue and incentivize sequencers to proactively cache hashed contracts, not the opposite.

**Comment by tacryt-socryp** [comment]
Update: smart.hoon has been fully pre-hashed and infinite loop issue is fixed. Merging into master now.

**Pull request merged**
