### PR TITLE
jold

### PR DESCRIPTION
**Pull request by hosted-fornet**
Before this PR, rice and eggs return untyped data when scried.

With this PR, JSON scries will return faced and typed data, provided contracts implement the `interface`/`types` following the spec in `lib/jolds.hoon`s docstring.

### CODE REVIEW

**Comment by hosted-fornet** [comment]
as of 863addd

```
$ export ZOD_COOKIE=$(curl -i -X POST localhost:8081/~/login -d 'password=lidlut-tabwed-pillex-ridrup' | grep set-cookie | awk '{print $2}' | awk -F ';' '{print $1}')
$ curl --cookie "$ZOD_COOKIE" localhost:8081/~/scry/uqbar/indexer/batch-order/0x0.json | jq
{
  "batch-order": [
    "0x6abe.bce3.c30d.02b2.b711.5a86.19f3.968b"
  ]
}
$ curl --cookie "$ZOD_COOKIE" localhost:8081/~/scry/uqbar/indexer/json/newest/hash/0x6abe.bce3.c30d.02b2.b711.5a86.19f3.968b.json | jq
 
...

               "0x61.7461.6461.7465.6d2d.7367.697a": {
                  "label": "metadata",
                  "salt": 1936157050,
                  "lord": "0x74.6361.7274.6e6f.632d.7367.697a",
                  "data": {
                    "metadata": "[545.108.595.435.344.701.968.725 4.671.834 18 100.000.000.000.000.000.000.000.000 [0 100.000.000.000.000.000.000.000.000] 1 0 0 1.936.157.050]"
                  },
                  "id": "0x61.7461.6461.7465.6d2d.7367.697a",
                  "is-rice": true,
                  "holder": "0x74.6361.7274.6e6f.632d.7367.697a",
                  "town-id": "0x0"
                },
... 
                "0x7590.0be1.cd45.6872.7675.365a.aad9.2178.0c57.877f.de0d.c7f8.a7d8.eb6e.a55e.6a03": {
                  "label": "account",
                  "salt": 1936157050,
                  "lord": "0x74.6361.7274.6e6f.632d.7367.697a",
                  "data": {
                    "account": [
                      {
                        "balance": 1e+26
                      },
                      {
                        "allowances": "0"
                      },
                      {
                        "metadata": "0x61.7461.6461.7465.6d2d.7367.697a"
                      },
                      {
                        "nonce": 0
                      }
                    ]
                  },
                  "id": "0x7590.0be1.cd45.6872.7675.365a.aad9.2178.0c57.877f.de0d.c7f8.a7d8.eb6e.a55e.6a03",
                  "is-rice": true,
                  "holder": "0x1a37.8abd.e505.f675.49e2.091f.769e.cc9e.013c.3ee6",
                  "town-id": "0x0"
                },
...
```

**Comment by hosted-fornet** [comment]
token metadta works as of 19d8bfb:
```
                "0x61.7461.6461.7465.6d2d.7367.697a": {
                  "label": "token-metadata",
                  "salt": 1936157050,
                  "lord": "0x74.6361.7274.6e6f.632d.7367.697a",
                  "data": {
                    "token-metadata": [
                      {
                        "name": "UQ| Tokens"
                      },
                      {
                        "symbol": "ZIG"
                      },
                      {
                        "decimals": 18
                      },
                      {
                        "supply": 1e+26
                      },
                      {
                        "cap": null
                      },
                      {
                        "mintable": false
                      },
                      {
                        "minters": null
                      },
                      {
                        "deployer-address": "0x0"
                      },
                      {
                        "salt": "0x7367.697a"
                      }
                    ]
                  },
```

**Comment by hosted-fornet** [comment]
Currently very fragile to incorrect data: the zigs metadata had a populated unit rather than a `~` in a field and it crashed the whole scry.

Need to make more robust: we have a fallback in the form of `crip noah`, so should avoid crashing if at all possible.

**Comment by hosted-fornet** [comment]
Big TODOs:

1. Make robust.
2. Multi-word types, non-recursive (like `unit`).
3. Multi-word types, recursive (`list`, `set`, `map`).
4. Use to re-add `grain-eggs` since we know what fields are hashes again.

**Comment by hosted-fornet** [comment]
TODOs 1-3 above are accomplished. 4 should be a separate PR. Specifically:
1. No more crashes; should fallback gracefully.
2. Added `unit`
3. Added general `set` and `list`. Added `map` where keys must be atoms, but values are general.

This PR is better than master in its current state. I'd also like to look at modifying the output of `+jold-full-tuple` to be a JSON object. The con is that this might make creation of the interface/types confusing, since there we represent Hoon tuples as arrays of single-item objects, since order matters for parsing. The pro is it is more what is expected (and ergonomic) for frontend usage.

**Comment by hosted-fornet** [comment]
Thanks to @workinglikeadogalldayonuqbar for the reference to [`+tree-noun-to-list`](https://github.com/urbit/urbit/blob/master/pkg/arvo/lib/pprint.hoon#L709-L717) which made `set`s and `map`s a breeze.

**Comment by hosted-fornet** [comment]
> I'd also like to look at modifying the output of `+jold-full-tuple` to be a JSON object. The con is that this might make creation of the interface/types confusing, since there we represent Hoon tuples as arrays of single-item objects, since order matters for parsing. The pro is it is more what is expected (and ergonomic) for frontend usage.

Done in 9a62d86

**Review by dr-frmr — APPROVED** [review]
This is sick

**Pull request merged**
