### PR TITLE
Hf/uqbar wallet polish 1

### PR DESCRIPTION
**Pull request by hosted-fornet**
* Route pokes through to `%wallet` (prepend path with %wallet).
* Pass through `%wallet` subscriptions (prepend path with %wallet).
* Unify style.
* Add `/hash`, `/batch-order` `%indexer` subscription paths.
* Add `%no-init` `%indexer` subscription suffixes.
* Add `%newest-*` types to `update:indexer`. Note this is a bit subtle: `/newest/egg` and `/newest/grain` queries will always return a `%newest-egg` or `%newest-grain`. But second-order queries like `/newest/holder` may return either `%newest-grain` OR `%grain`, because a holder may hold multiple grains.
* Move existing subscriptions from unresponsive indexers to live indexers.

Future work:
* Change `update:indexer` type tags, e.g. `%grain` -> `%grains` and `%newest-grain` -> `%grain`. This will break the current interface since the tag, e.g., `%grain` will change, and so will require coordination with fabnev.
* Additional subscription fallback improvements. Specifically, would be nice if we could somehow query for the subscription data we may have missed while our provider was down. For example, say our app `%foo` is subscribed through `%uqbar` for `grain` `0xdead.beef`, but then the `%indexer` goes down. After some time period, `%uqbar` will move the subscription over to a fallback `%indexer` if one is up. But from time t_{down} when the original `%indexer` went down to time t_{fallback}, when `%uqbar` subscribes to the new `%indexer`, we may have missed updates.

### CODE REVIEW

**Comment by hosted-fornet** [comment]
@dr-frmr while testing one of these commits noticed that nonces got bumped improperly when submitting two txs to one batch from same account, one of which was `%submit-custom`. I'll get more details and perhaps fix tomorrow, but thought I'd let you know I had seen this.

**Comment by hosted-fornet** [comment]
@dr-frmr  Regarding the bug I mention upthread, I see what is causing the problem: [mill.hoon L71-73](https://github.com/uqbar-dao/ziggurat/blob/79937b93368e8530d33499f5c7b84e0a80643546/lib/zig/mill.hoon#L71-L73). If I submit two txs in one block from the same account, one with nonce=N and one with nonce=N+1, and nonce=N+1 has a higher fee rate than nonce=N, mill will attempt to execute them out of order, and so N+1 will fail.

**Comment by hosted-fornet** [comment]
> @dr-frmr Regarding the bug I mention upthread, I see what is causing the problem: [mill.hoon L71-73](https://github.com/uqbar-dao/ziggurat/blob/79937b93368e8530d33499f5c7b84e0a80643546/lib/zig/mill.hoon#L71-L73). If I submit two txs in one block from the same account, one with nonce=N and one with nonce=N+1, and nonce=N+1 has a higher fee rate than nonce=N, mill will attempt to execute them out of order, and so N+1 will fail.

To reproduce:
1. Start new fakeship.
2. Start rollup, etc.
3. Submit a zigs send.
4. Submit the batch with `:sequencer|batch`
5. Submit a custom tx, and then a zigs send.
6. Submit the batch

Step 6 should lead to output like "incorrect nonce".

In copy-pastable Dojo code:

```
:rollup|activate
:sequencer|init our 0x0 0xc9f8.722e.78ae.2e83.0dd9.e8b9.db20.f36a.1bc4.c704.4758.6825.c463.1ab6.daee.e608
:indexer &set-sequencer [our %sequencer]
:indexer &set-rollup [our %rollup]
:uqbar|set-sources 0x0 ~[our]
:uqbar &zig-wallet-poke [%import-seed 'uphold apology rubber cash parade wonder shuffle blast delay differ help priority bleak ugly fragile flip surge shield shed mistake matrix hold foam shove' 'squid' 'nickname']

:uqbar &zig-wallet-poke [%submit from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 to=0x74.6361.7274.6e6f.632d.7367.697a town=0x0 gas=[1 1.000.000] [%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=123.456 grain=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6]]
:sequencer|batch

:uqbar &zig-wallet-poke [%submit-custom from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 to=0x74.6361.7274.6e6f.632d.7367.697a town=0x0 gas=[1 1.000.000] yolk='[%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=69.000 from-account=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6 to-account=`0xd79b.98fc.7d3b.d71b.4ac9.9135.ffba.cc6c.6c98.9d3b.8aca.92f8.b07e.a0a5.3d8f.a26c]']
:uqbar &zig-wallet-poke [%submit from=0x7a9a.97e0.ca10.8e1e.273f.0000.8dca.2b04.fc15.9f70 to=0x74.6361.7274.6e6f.632d.7367.697a town=0x0 gas=[1 1.000.000] [%give to=0xd6dc.c8ff.7ec5.4416.6d4e.b701.d1a6.8e97.b464.76de amount=123.456 grain=0x89a0.89d8.dddf.d13a.418c.0d93.d4b4.e7c7.637a.d56c.96c0.7f91.3a14.8174.c7a7.71e6]]
:sequencer|batch
```

**Comment by dr-frmr** [comment]
Ah I see.. this is something I considered but punted on cause I didn't want to have to sort all transactions twice. Need to change the sorting algorithm for eggs

**Comment by dr-frmr** [comment]
Since this is an issue with mill we can address it in another branch, this all looks good

**Review by dr-frmr — APPROVED** [review]

**Pull request merged**
