### PR TITLE
multisig: revive

### PR DESCRIPTION
**Pull request by ynx0**
This PR attempts to revive the `multisig.hoon` contract.
To run the associated tests, run `-test ~[/=zig=/tests/contracts/multisig]` at the dojo.

### CODE REVIEW

**Comment by dr-frmr** [comment]
I just merged dr/wallets-and-contracts to master, so you can probably rebase to that here

**Comment by dr-frmr** [comment]
Contract is looking good

**Comment by ynx0** [comment]
@dr-frmr as of now, there is test coverage for all `actions` of the multisig contract (positive cases), which you can run with `-test ~[/=zig=/tests/contracts/multisig]` PTAL

**Review by dr-frmr — APPROVED** [review]

**Comment by ynx0** [comment]
@tacryt-socryp I'm gonna go ahead and merge this PR for the sake of moving things along, but if you do have any thoughts please feel free to leave a review and I can make a new PR addressing the changes.

**Pull request merged**
