### PR TITLE
merk: add `+key` to `bi`

### PR DESCRIPTION
**Pull request by ynx0**
Ended up being useful during debugging. Adapted from `key:by` so it should be correct.

### CODE REVIEW

**Comment by dr-frmr** [comment]
Nice, can we call it `key` though? Just to keep in line with other operations having same names as `map`.

**Comment by ynx0** [comment]
Oh yeah should’ve said but if you do that everything breaks because it
clashes with the `key` mold defined earlier.

**Comment by dr-frmr** [comment]
Ah, I see. I'm inclined to say we change the internal type in order to keep the tree interface the same..

**Comment by ynx0** [comment]
Ok so I just realized that apparently there are two different instances of `merk` and `bi`, one in `merk.hoon` and one in `smart.hoon`, and that sent me on a goose chase for a bit.

Which one do we want to keep? I guess both is also an answer in which case I could modify both for the time being but that seems undesirable long term.

**Comment by dr-frmr** [comment]
Yes, both are necessary. The version inside the smart contract library must never be used outside it, since the jet tagging conventions are different and you will end up running merk operations completely unjetted, which takes forever.

**Review by dr-frmr — APPROVED** [review]
This looks good

**Pull request merged**
